function latex_new = latexTable_add_row_bottom(latex, row_to_add, n_span, options)
%LATEXTABLE_ADD_ROW_BOTTOM Add a row at the bottom of the latex table generated
%by 'latexTable' (Dunisch, 2016)
%   latex: the struct generated by 'latexTable'
%   row_to_add: content of the row to add in cell array format
    arguments
        latex
        row_to_add (:, 1) cell
        n_span (1, 1) {mustBeInteger} = 1
        options.threeparttable logical = false
    end
%     index_before_end_tabular = find(startsWith(latex, '\end{tabular}'));
%     latex_before_end_tabular = latex(1:(index_before_end_tabular - 1));
%     latex_after_end_tabular = latex(index_before_end_tabular:end);
    if options.threeparttable
        new_line = strcat({'\item '}, row_to_add);
        index_caption = find(startsWith(latex, '\caption'));
        index_begin_tabular = find(startsWith(latex, '\begin{tabular}'));
        index_end_tabular = find(startsWith(latex, '\end{tabular}'));
        index_label = find(startsWith(latex, '\label'));
        if ismissing(index_caption)
            index_begin = index_begin_tabular;
        elseif index_caption > index_begin_tabular
            index_begin = index_begin_tabular;
        else
            index_begin = index_caption;
        end
        if ismissing(index_label)
            index_end = index_end_tabular;
        elseif index_label < index_end_tabular
            index_end = index_end_tabular;
        else
            index_end = index_label;
        end
        latex_new = [
            latex(1:(index_begin - 1));
            '\begin{threeparttable}[b]';
            latex(index_begin:index_end);
            '\begin{tablenotes}';
            new_line;
            '\end{tablenotes}';
            '\end{threeparttable}';
            latex((index_end + 1):end)
            ];
    else
        new_line = strcat(['\multicolumn{', num2str(n_span), '}{l}{'], row_to_add , '}\\');
        index_end_tabular = find(startsWith(latex, '\end{tabular}'));
        latex_new = [
            latex(1:(index_end_tabular - 1));
            new_line;
            latex(index_end_tabular:end)
            ];
    end
end