function output = latexTable_save(latex, filename, permission)
%LATEXTABLE_SAVE Save the struct generated by 'latexTable' (Dunisch, 2016)
%   latex: the struct generated by 'latexTable'
%   filename: target address of the file to save
%   permission: type of access ('w' for new file, 'a' for appending)
    fid = fopen(filename, permission);
    nrows = size(latex, 1);
    for row = 1:nrows
        fprintf(fid, '%s\n', latex{row, :});
    end
    fclose(fid);
    return
end